name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print build information
        run: "echo head_ref: ${{ github.head_ref }}, ref: ${{ github.ref }}"
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Set up staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest 

      - name: Set up workflowcheck
        run: go install go.temporal.io/sdk/contrib/tools/workflowcheck@latest

      - name: Staticcheck sending-signals-external
        run: staticcheck .
        working-directory: exercises/sending-signals-external/solution/worker

      - name: Staticcheck sending-signals-client
        run: staticcheck .
        working-directory: exercises/sending-signals-client/solution/worker

      - name: Staticcheck querying-workflows
        run: staticcheck .
        working-directory: exercises/querying-workflows/solution/worker

      - name: Staticcheck async-activity-completion
        run: staticcheck .
        working-directory: exercises/async-activity-completion/solution/worker

      - name: Workflowcheck sending-signals-external
        run: workflowcheck -show-pos .
        working-directory: exercises/sending-signals-external/solution/worker

      - name: Workflowcheck sending-signals-client
        run: workflowcheck -show-pos .
        working-directory: exercises/sending-signals-client/solution/worker

      - name: Workflowcheck querying-workflows
        run: workflowcheck -show-pos .
        working-directory: exercises/querying-workflows/solution/worker

      - name: Workflowcheck async-activity-completion
        run: workflowcheck -show-pos .
        working-directory: exercises/async-activity-completion/solution/worker

      - name: Build sending-signals-external
        run: go build
        working-directory: exercises/sending-signals-external/solution/worker

      - name: Build sending-signals-client
        run: go build
        working-directory: exercises/sending-signals-client/solution/worker

      - name: Build querying-workflows
        run: go build
        working-directory: exercises/querying-workflows/solution/worker

      - name: Build async-activity-completion
        run: go build
        working-directory: exercises/async-activity-completion/solution/worker
